#!/usr/bin/env bash

tcframeConv_printUsage() {
    echo "usage: tcframeConv <command>"
    echo ""
    echo "Available commands:"
    echo "  build         Compress tcframe file into zip"
    echo "  create        Create tcframe folder inside current directory"
    echo "  version       Print tcframe version"
}

tcframeConv_build() {
    python3 "$TCFRAME_CONV_HOME/src/script.py"
    echo "tcframeConv: testcases successfully compressed with Kattis Problem Format"
}

tcframeConv_create() {
    cp -r "$TCFRAME_CONV_HOME/src/tc/" "$PWD/tc"
}

tcframeConv_version() {
    echo "tcframeToKattis 1.0.2"
    echo "Personal usage only"
}

tcframeConv_main() {
    if [ -z "$TCFRAME_CONV_HOME" ]; then
        echo "tcframeConv: error: env variable TCFRAME_CONV_HOME not set"
        exit 1
    fi

    if [ $# -eq 0 ]; then
        tcframeConv_printUsage
        exit 1
    fi

    command=$1

    if [ $1 = "build" ]; then
        tcframeConv_build
    elif [ $1 = "create" ]; then
        tcframeConv_create
    elif [ $1 = "version" ]; then
        tcframeConv_version
    else
        tcframeConv_printUsage
        exit 1
    fi
}

tcframeConv_main $@