#!/usr/bin/env bash

tcframeConv_printUsage() {
  echo -e "usage: tcframeConv <command>"
  echo -e ""
  echo -e "Available commands:"
  echo -e "  build         Compress tcframe file into zip"
  echo -e "  version       Print tcframe version"
}

tcframeConv_build() {
  python3 "$TCFRAME_CONV_HOME/libs/runner.py"
}

tcframeConv_create() {
  echo -e "tcframeConv: this command is deprecated"
}

tcframeConv_version() {
  echo -e "tcframeToKattis 1.1.0"
  echo -e "Personal usage only"
}

tcframeConv_main() {
  if [ -z "$TCFRAME_CONV_HOME" ]; then
    echo -e "tcframeConv: error: env variable TCFRAME_CONV_HOME not set"
    exit 1
  fi

  if [ $# -eq 0 ]; then
    tcframeConv_printUsage
    exit 1
  fi

  command=$1

  if [ $1 = "build" ]; then
    tcframeConv_build
  elif [ $1 = "create" ]; then
    tcframeConv_create
  elif [ $1 = "version" ]; then
    tcframeConv_version
  else
    tcframeConv_printUsage
    exit 1
  fi
}

tcframeConv_main $@
